SEED_MOVIES = [
    # Action Movies
    {"title": "The Dark Knight", "year": 2008, "genre": "Action", 
     "description": "Batman faces the Joker in this epic crime saga.", 
     "rating": 9.0, "runtime": 152},
    {"title": "Mad Max: Fury Road", "year": 2015, "genre": "Action", 
     "description": "In a post-apocalyptic wasteland, Max teams up with Furiosa.", 
     "rating": 8.1, "runtime": 120},
    {"title": "John Wick", "year": 2014, "genre": "Action", 
     "description": "An ex-hitman comes out of retirement to track down the gangsters.", 
     "rating": 7.4, "runtime": 101},
    {"title": "Die Hard", "year": 1988, "genre": "Action", 
     "description": "A New York cop battles terrorists in a Los Angeles skyscraper.", 
     "rating": 8.2, "runtime": 132},
    {"title": "Mission: Impossible", "year": 1996, "genre": "Action", 
     "description": "Ethan Hunt is framed and must clear his name.", 
     "rating": 7.1, "runtime": 110},
    {"title": "The Matrix", "year": 1999, "genre": "Action", 
     "description": "A hacker discovers reality is a computer simulation.", 
     "rating": 8.7, "runtime": 136},
    {"title": "Gladiator", "year": 2000, "genre": "Action", 
     "description": "A betrayed Roman general seeks revenge as a gladiator.", 
     "rating": 8.5, "runtime": 155},
    {"title": "Speed", "year": 1994, "genre": "Action", 
     "description": "A cop must keep a bus above 50 mph to prevent a bomb from exploding.", 
     "rating": 7.2, "runtime": 116},

    # Comedy Movies
    {"title": "The Grand Budapest Hotel", "year": 2014, "genre": "Comedy", 
     "description": "The adventures of a legendary concierge and his protégé.", 
     "rating": 8.1, "runtime": 99},
    {"title": "Superbad", "year": 2007, "genre": "Comedy", 
     "description": "Two co-dependent high school seniors set out to score alcohol.", 
     "rating": 7.6, "runtime": 113},
    {"title": "The Hangover", "year": 2009, "genre": "Comedy", 
     "description": "Three friends wake up from a bachelor party with no memory.", 
     "rating": 7.7, "runtime": 100},
    {"title": "Anchorman", "year": 2004, "genre": "Comedy", 
     "description": "Ron Burgundy is San Diego's top-rated newsman in the 1970s.", 
     "rating": 7.2, "runtime": 94},
    {"title": "Groundhog Day", "year": 1993, "genre": "Comedy", 
     "description": "A weatherman finds himself living the same day over and over.", 
     "rating": 8.0, "runtime": 101},
    {"title": "Zoolander", "year": 2001, "genre": "Comedy", 
     "description": "A male model uncovers a conspiracy to assassinate the Prime Minister.", 
     "rating": 6.5, "runtime": 90},
    {"title": "Wedding Crashers", "year": 2005, "genre": "Comedy", 
     "description": "Two friends crash weddings to meet women.", 
     "rating": 7.0, "runtime": 119},
    {"title": "Dumb and Dumber", "year": 1994, "genre": "Comedy", 
     "description": "Two dim-witted friends go on a cross-country trip.", 
     "rating": 7.3, "runtime": 107},

    # Drama Movies
    {"title": "The Shawshank Redemption", "year": 1994, "genre": "Drama", 
     "description": "Two imprisoned men bond over years, finding solace in acts of decency.", 
     "rating": 9.3, "runtime": 142},
    {"title": "Forrest Gump", "year": 1994, "genre": "Drama", 
     "description": "The presidencies of Kennedy and Johnson through the eyes of Forrest Gump.", 
     "rating": 8.8, "runtime": 142},
    {"title": "The Godfather", "year": 1972, "genre": "Drama", 
     "description": "The aging patriarch of an organized crime dynasty.", 
     "rating": 9.2, "runtime": 175},
    {"title": "Good Will Hunting", "year": 1997, "genre": "Drama", 
     "description": "A janitor at MIT has a gift for mathematics.", 
     "rating": 8.3, "runtime": 126},
    {"title": "A Beautiful Mind", "year": 2001, "genre": "Drama", 
     "description": "The life of John Nash, a Nobel Laureate in Economics.", 
     "rating": 8.2, "runtime": 135},
    {"title": "The Pursuit of Happyness", "year": 2006, "genre": "Drama", 
     "description": "A struggling salesman takes custody of his son.", 
     "rating": 8.0, "runtime": 117},
    {"title": "12 Years a Slave", "year": 2013, "genre": "Drama", 
     "description": "A free black man is abducted and sold into slavery.", 
     "rating": 8.1, "runtime": 134},
    {"title": "The Green Mile", "year": 1999, "genre": "Drama", 
     "description": "Death row guards at a penitentiary in the 1930s.", 
     "rating": 8.6, "runtime": 189},

    # Horror Movies
    {"title": "The Exorcist", "year": 1973, "genre": "Horror", 
     "description": "A young girl becomes possessed by demons.", 
     "rating": 8.0, "runtime": 122},
    {"title": "Halloween", "year": 1978, "genre": "Horror", 
     "description": "Michael Myers escapes and stalks teenage babysitters.", 
     "rating": 7.7, "runtime": 91},
    {"title": "A Nightmare on Elm Street", "year": 1984, "genre": "Horror", 
     "description": "Freddy Krueger attacks teenagers in their dreams.", 
     "rating": 7.5, "runtime": 101},
    {"title": "The Shining", "year": 1980, "genre": "Horror", 
     "description": "A family heads to an isolated hotel where sinister forces await.", 
     "rating": 8.4, "runtime": 146},
    {"title": "Get Out", "year": 2017, "genre": "Horror", 
     "description": "A young black man visits his white girlfriend's parents.", 
     "rating": 7.7, "runtime": 104},
    {"title": "Hereditary", "year": 2018, "genre": "Horror", 
     "description": "A grieving family is haunted by tragedy and disturbing secrets.", 
     "rating": 7.3, "runtime": 127},
    {"title": "The Conjuring", "year": 2013, "genre": "Horror", 
     "description": "Paranormal investigators help a family terrorized by a dark presence.", 
     "rating": 7.5, "runtime": 112},
    {"title": "Scream", "year": 1996, "genre": "Horror", 
     "description": "A killer stalks high school students in Woodsboro.", 
     "rating": 7.3, "runtime": 111},

    # Sci-Fi Movies
    {"title": "Inception", "year": 2010, "genre": "Sci-Fi", 
     "description": "A thief who enters people's dreams to steal secrets.", 
     "rating": 8.8, "runtime": 148},
    {"title": "Blade Runner 2049", "year": 2017, "genre": "Sci-Fi", 
     "description": "A young blade runner discovers a secret that could plunge society into chaos.", 
     "rating": 8.0, "runtime": 164},
    {"title": "Interstellar", "year": 2014, "genre": "Sci-Fi", 
     "description": "A team of explorers travel through a wormhole in space.", 
     "rating": 8.6, "runtime": 169},
    {"title": "Star Wars: A New Hope", "year": 1977, "genre": "Sci-Fi", 
     "description": "Luke Skywalker joins forces with a Jedi Knight to rescue a princess.", 
     "rating": 8.6, "runtime": 121},
    {"title": "Alien", "year": 1979, "genre": "Sci-Fi", 
     "description": "The crew of a commercial spacecraft encounters a deadly alien.", 
     "rating": 8.4, "runtime": 117},
    {"title": "The Terminator", "year": 1984, "genre": "Sci-Fi", 
     "description": "A cyborg assassin is sent back in time to kill Sarah Connor.", 
     "rating": 8.0, "runtime": 107},
    {"title": "Back to the Future", "year": 1985, "genre": "Sci-Fi", 
     "description": "Marty McFly travels back in time in a DeLorean time machine.", 
     "rating": 8.5, "runtime": 116},
    {"title": "E.T. the Extra-Terrestrial", "year": 1982, "genre": "Sci-Fi", 
     "description": "A young boy befriends an alien stranded on Earth.", 
     "rating": 7.8, "runtime": 115},

    # Thriller Movies
    {"title": "The Silence of the Lambs", "year": 1991, "genre": "Thriller", 
     "description": "A young FBI cadet must confide in incarcerated Dr. Hannibal Lecter.", 
     "rating": 8.6, "runtime": 118},
    {"title": "Seven", "year": 1995, "genre": "Thriller", 
     "description": "Two detectives hunt a serial killer who uses the seven deadly sins.", 
     "rating": 8.6, "runtime": 127},
    {"title": "Gone Girl", "year": 2014, "genre": "Thriller", 
     "description": "A husband becomes the prime suspect in his wife's disappearance.", 
     "rating": 8.1, "runtime": 149},
    {"title": "Zodiac", "year": 2007, "genre": "Thriller", 
     "description": "The search for the Zodiac Killer who terrorized San Francisco.", 
     "rating": 7.7, "runtime": 157},
    {"title": "Shutter Island", "year": 2010, "genre": "Thriller", 
     "description": "A U.S. Marshal investigates a disappearance at a psychiatric facility.", 
     "rating": 8.2, "runtime": 138},
    {"title": "No Country for Old Men", "year": 2007, "genre": "Thriller", 
     "description": "A hunter stumbles upon a drug deal gone wrong.", 
     "rating": 8.1, "runtime": 122},
    {"title": "Prisoners", "year": 2013, "genre": "Thriller", 
     "description": "A father searches for his missing daughter.", 
     "rating": 8.1, "runtime": 153},
    {"title": "The Departed", "year": 2006, "genre": "Thriller", 
     "description": "An undercover cop and a police informant try to identify each other.", 
     "rating": 8.5, "runtime": 151},

    # Romance Movies
    {"title": "The Notebook", "year": 2004, "genre": "Romance", 
     "description": "An elderly man tells the story of a couple's enduring love.", 
     "rating": 7.8, "runtime": 123},
    {"title": "Titanic", "year": 1997, "genre": "Romance", 
     "description": "A seventeen-year-old aristocrat falls in love with a poor artist.", 
     "rating": 7.8, "runtime": 194},
    {"title": "Casablanca", "year": 1942, "genre": "Romance", 
     "description": "A cynical nightclub owner aids his former lover and her husband.", 
     "rating": 8.5, "runtime": 102},
    {"title": "When Harry Met Sally", "year": 1989, "genre": "Romance", 
     "description": "Harry and Sally debate whether men and women can be friends.", 
     "rating": 7.6, "runtime": 96},
    {"title": "The Princess Bride", "year": 1987, "genre": "Romance", 
     "description": "A farmhand must rescue his true love from an evil prince.", 
     "rating": 8.0, "runtime": 98},
    {"title": "Pretty Woman", "year": 1990, "genre": "Romance", 
     "description": "A businessman hires a prostitute to accompany him to social events.", 
     "rating": 7.0, "runtime": 119},
    {"title": "Ghost", "year": 1990, "genre": "Romance", 
     "description": "A murdered man's spirit stays behind to protect his girlfriend.", 
     "rating": 7.0, "runtime": 127},
    {"title": "Sleepless in Seattle", "year": 1993, "genre": "Romance", 
     "description": "A widower's son calls a radio talk show to find his father a partner.", 
     "rating": 6.8, "runtime": 105}
]
